services:
  frontend:
    image: ${FRONTEND_RUNTIME_IMAGE_NAME}
    container_name: frontend
    restart: unless-stopped
    ports:
     - '80:80'
    networks:
      - option_volatility_dashboard

  backend:
    image: ${BACKEND_RUNTIME_IMAGE_NAME}
    container_name: backend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - option_volatility_dashboard

networks:
  option_volatility_dashboard:
