version: "3"
services:
  option_volatility_api:
    image: shadrinsergey/option_volatility_dashboard:0.0.1
    container_name: option_volatility_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
     - '5000:5000'
    networks:
      - option_volatility_dashboard

networks:
  option_volatility_dashboard:
