services:
  backend:
    image: ${RUNTIME_IMAGE_NAME}
    container_name: backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
     - '5000:5000'
    networks:
      - option_volatility_dashboard

networks:
  option_volatility_dashboard:
