name: Build Runtime Docker Image And Redeploy

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: shadrinsergey
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push runtime docker image
        run: ./bin/build-runtime-image.sh

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.KEY }}
          script: 'sudo /var/www/redeploy.sh'
