name: Build Runtime Docker Image And Redeploy

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: shadrinsergey
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push runtime docker image
        run: ./bin/build-runtime-image.sh

      - name: Install SSH client
        run: sudo apt-get install openssh-client -y

      - name: Run remote shell script
        run: |
          ssh -o StrictHostKeyChecking=no "${REMOTE_USER}@${REMOTE_HOST}" 'sudo /var/www/redeploy.sh'
        env:
          REMOTE_USER: ${{ env.REMOTE_USER }}
          REMOTE_HOST: ${{ env.REMOTE_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
