name: Build Runtime Docker Image

on:
  push:
    branches: [ "master" ]
    paths:
      - 'src'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: ./bin/build-runtime-image.sh
