name: Build Runtime Docker Image

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: shadrinsergey
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push runtime docker image
        run: ./bin/build-runtime-image.sh
